
import streamlit as st
import os
from google import genai
from dotenv import load_dotenv
import fitz  # PyMuPDF
from docx import Document
from io import BytesIO

# 1. PAGE CONFIGURATION
st.set_page_config(page_title="CA AI Assistant", layout="centered")
st.title("⚖️ Tax Notice AI-Responder")
st.caption("Professional Drafting Tool for Chartered Accountants")

# 2. SECURE API KEY HANDLING
# First check Streamlit Cloud Secrets, then local .env, then sidebar
if "GEMINI_API_KEY" in st.secrets:
    final_key = st.secrets["GEMINI_API_KEY"]
else:
    load_dotenv()
    final_key = os.getenv("GEMINI_API_KEY")

user_key = st.sidebar.text_input("Manual API Key (if needed)", type="password")
if user_key:
    final_key = user_key

# --- 3. CLEAN WORD DOCUMENT FUNCTION ---
def create_docx(text):
    doc = Document()
    
    # Professional Header
    header = doc.add_heading('DRAFT RESPONSE TO INCOME TAX NOTICE', 0)
    header.alignment = 1 # Center aligned
    
    doc.add_paragraph("Generated by: Krish Janwani & Associates (AI Assistant)")
    doc.add_paragraph("-" * 50)
    
    # CLEANING THE TEXT: Removes messy ** and ### from AI output
    clean_text = text.replace('**', '').replace('###', '').replace('---', '')
    
    # Add the cleaned content
    para = doc.add_paragraph(clean_text)
    
    # Save to memory buffer
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()

# 4. USER INTERFACE
file = st.file_uploader("Upload Tax Notice (PDF)", type="pdf")

if file and final_key:
    # Extract text from PDF
    try:
        pdf_data = fitz.open(stream=file.read(), filetype="pdf")
        notice_text = "".join([page.get_text() for page in pdf_data])
        st.success("Notice content extracted successfully.")
    except Exception as e:
        st.error(f"PDF Read Error: {e}")

    if st.button("Generate Professional Draft"):
        try:
            # Connect to Gemini 1.5 Flash using the 2026 Client
            client = genai.Client(api_key=final_key)
            
            with st.spinner("Drafting legal response..."):
                response = client.models.generate_content(
                    model="gemini-1.5-flash", 
                    contents=f"Act as a senior Chartered Accountant. Draft a formal, professional response to this tax notice: {notice_text}. Use a polite but firm legal tone."
                )
            
            draft_content = response.text
            
            # Show draft on screen
            st.subheader("Preview Draft")
            st.write(draft_content)
            
            # --- WORD DOWNLOAD BUTTON ---
            st.divider()
            docx_data = create_docx(draft_content)
            st.download_button(
                label="📥 Download Clean Word Document (.docx)",
                data=docx_data,
                file_name="Tax_Notice_Reply_Clean.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
                
        except Exception as e:
            # Common error handling for 403 (Leaked/Invalid Key)
            if "403" in str(e):
                st.error("API Error: Your key is invalid or has been blocked by Google. Please update your Secrets with a new key.")
            else:
                st.error(f"System Error: {e}")
            
elif not final_key:
    st.warning("System Waiting: Please provide a valid Gemini API Key to proceed.")

