import streamlit as st
import os
from google import genai
from dotenv import load_dotenv
import fitz 
from docx import Document
from io import BytesIO

# 1. SETUP
load_dotenv()
st.set_page_config(page_title="CA AI Assistant", layout="centered")
st.title("⚖️ Tax Notice AI-Responder")

# 2. API KEY HANDLING
api_key = os.getenv("GEMINI_API_KEY")
user_key = st.sidebar.text_input("Enter API Key (Optional)", type="password")
final_key = user_key if user_key else api_key

# --- HELPER FUNCTION FOR WORD EXPORT ---
def create_docx(text):
    doc = Document()
    # Adding a professional header to the Word file
    doc.add_heading('Draft Response to Income Tax Notice', 0)
    doc.add_paragraph("Generated by CA AI Assistant")
    doc.add_paragraph("-" * 30)
    
    # Adding the AI content
    doc.add_paragraph(text)
    
    # Saving to memory buffer
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()

# 3. INTERFACE
file = st.file_uploader("Upload Tax Notice (PDF)", type="pdf")

if file and final_key:
    # Read the uploaded PDF
    doc = fitz.open(stream=file.read(), filetype="pdf")
    notice_text = "".join([page.get_text() for page in doc])
    st.info("Notice Content Loaded Successfully.")
    
    if st.button("Generate Draft"):
        try:
            # Connect to Gemini 2.5 Flash
            client = genai.Client(api_key=final_key)
            response = client.models.generate_content(
                model="gemini-2.5-flash", 
                contents=f"Act as a Chartered Accountant. Draft a formal, detailed reply for this tax notice: {notice_text}"
            )
            draft_content = response.text
            
            # Displaying the draft on screen
            st.success("Draft Generated!")
            st.markdown(draft_content)
            
            # --- SINGLE DOWNLOAD BUTTON ---
            st.divider()
            docx_data = create_docx(draft_content)
            st.download_button(
                label="📥 Download Draft as Word (.docx)",
                data=docx_data,
                file_name="Tax_Notice_Reply.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
                
        except Exception as e:
            st.error(f"Error: {e}")
            
elif not final_key:
    st.warning("Please provide an API Key in the sidebar to begin.")